# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from serial/HP.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class HP(genpy.Message):
  _md5sum = "2f1de7f65b9e758a9b89a73d0d3bd446"
  _type = "serial/HP"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# Rune.msg
## From CS to CV : Health points of all robots

# Message

uint16 foe_hero
uint16 foe_standard1
uint16 foe_standard2
uint16 foe_sentry

uint16 ally_hero
uint16 ally_standard1
uint16 ally_standard2
uint16 ally_sentry
"""
  __slots__ = ['foe_hero','foe_standard1','foe_standard2','foe_sentry','ally_hero','ally_standard1','ally_standard2','ally_sentry']
  _slot_types = ['uint16','uint16','uint16','uint16','uint16','uint16','uint16','uint16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       foe_hero,foe_standard1,foe_standard2,foe_sentry,ally_hero,ally_standard1,ally_standard2,ally_sentry

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(HP, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.foe_hero is None:
        self.foe_hero = 0
      if self.foe_standard1 is None:
        self.foe_standard1 = 0
      if self.foe_standard2 is None:
        self.foe_standard2 = 0
      if self.foe_sentry is None:
        self.foe_sentry = 0
      if self.ally_hero is None:
        self.ally_hero = 0
      if self.ally_standard1 is None:
        self.ally_standard1 = 0
      if self.ally_standard2 is None:
        self.ally_standard2 = 0
      if self.ally_sentry is None:
        self.ally_sentry = 0
    else:
      self.foe_hero = 0
      self.foe_standard1 = 0
      self.foe_standard2 = 0
      self.foe_sentry = 0
      self.ally_hero = 0
      self.ally_standard1 = 0
      self.ally_standard2 = 0
      self.ally_sentry = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_8H().pack(_x.foe_hero, _x.foe_standard1, _x.foe_standard2, _x.foe_sentry, _x.ally_hero, _x.ally_standard1, _x.ally_standard2, _x.ally_sentry))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.foe_hero, _x.foe_standard1, _x.foe_standard2, _x.foe_sentry, _x.ally_hero, _x.ally_standard1, _x.ally_standard2, _x.ally_sentry,) = _get_struct_8H().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_8H().pack(_x.foe_hero, _x.foe_standard1, _x.foe_standard2, _x.foe_sentry, _x.ally_hero, _x.ally_standard1, _x.ally_standard2, _x.ally_sentry))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.foe_hero, _x.foe_standard1, _x.foe_standard2, _x.foe_sentry, _x.ally_hero, _x.ally_standard1, _x.ally_standard2, _x.ally_sentry,) = _get_struct_8H().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_8H = None
def _get_struct_8H():
    global _struct_8H
    if _struct_8H is None:
        _struct_8H = struct.Struct("<8H")
    return _struct_8H
