# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from serial/Target.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class Target(genpy.Message):
  _md5sum = "31aff261d89d039028ca56aec375fe72"
  _type = "serial/Target"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# Target.msg
## From CV to CS : Coordinates of the current target

# Message

time stamp
bool located

uint16 theta    # milli-ad
int16 phi       # millirad
uint16 dist     # mm
"""
  __slots__ = ['stamp','located','theta','phi','dist']
  _slot_types = ['time','bool','uint16','int16','uint16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       stamp,located,theta,phi,dist

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Target, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.stamp is None:
        self.stamp = genpy.Time()
      if self.located is None:
        self.located = False
      if self.theta is None:
        self.theta = 0
      if self.phi is None:
        self.phi = 0
      if self.dist is None:
        self.dist = 0
    else:
      self.stamp = genpy.Time()
      self.located = False
      self.theta = 0
      self.phi = 0
      self.dist = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2IBHhH().pack(_x.stamp.secs, _x.stamp.nsecs, _x.located, _x.theta, _x.phi, _x.dist))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 15
      (_x.stamp.secs, _x.stamp.nsecs, _x.located, _x.theta, _x.phi, _x.dist,) = _get_struct_2IBHhH().unpack(str[start:end])
      self.located = bool(self.located)
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2IBHhH().pack(_x.stamp.secs, _x.stamp.nsecs, _x.located, _x.theta, _x.phi, _x.dist))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 15
      (_x.stamp.secs, _x.stamp.nsecs, _x.located, _x.theta, _x.phi, _x.dist,) = _get_struct_2IBHhH().unpack(str[start:end])
      self.located = bool(self.located)
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2IBHhH = None
def _get_struct_2IBHhH():
    global _struct_2IBHhH
    if _struct_2IBHhH is None:
        _struct_2IBHhH = struct.Struct("<2IBHhH")
    return _struct_2IBHhH
