# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from tracking/Tracklets.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import tracking.msg

class Tracklets(genpy.Message):
  _md5sum = "eaf004b7dd6cb035732a86956a387ae0"
  _type = "tracking/Tracklets"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# Tracklets.msg
## List of tracked bounding boxes

# Header header
Tracklet[] tracklets
================================================================================
MSG: tracking/Tracklet
# Tracklet.msg
## Bounding box with class

# Constants

# TODO
# uint8 car
# uint8 armor_module
# ...

# Bounding box
float32 x
float32 y
float32 w
float32 h

# class
uint8 cls

float32 confidence"""
  __slots__ = ['tracklets']
  _slot_types = ['tracking/Tracklet[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       tracklets

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Tracklets, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.tracklets is None:
        self.tracklets = []
    else:
      self.tracklets = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.tracklets)
      buff.write(_struct_I.pack(length))
      for val1 in self.tracklets:
        _x = val1
        buff.write(_get_struct_4fBf().pack(_x.x, _x.y, _x.w, _x.h, _x.cls, _x.confidence))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.tracklets is None:
        self.tracklets = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.tracklets = []
      for i in range(0, length):
        val1 = tracking.msg.Tracklet()
        _x = val1
        start = end
        end += 21
        (_x.x, _x.y, _x.w, _x.h, _x.cls, _x.confidence,) = _get_struct_4fBf().unpack(str[start:end])
        self.tracklets.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.tracklets)
      buff.write(_struct_I.pack(length))
      for val1 in self.tracklets:
        _x = val1
        buff.write(_get_struct_4fBf().pack(_x.x, _x.y, _x.w, _x.h, _x.cls, _x.confidence))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.tracklets is None:
        self.tracklets = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.tracklets = []
      for i in range(0, length):
        val1 = tracking.msg.Tracklet()
        _x = val1
        start = end
        end += 21
        (_x.x, _x.y, _x.w, _x.h, _x.cls, _x.confidence,) = _get_struct_4fBf().unpack(str[start:end])
        self.tracklets.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4fBf = None
def _get_struct_4fBf():
    global _struct_4fBf
    if _struct_4fBf is None:
        _struct_4fBf = struct.Struct("<4fBf")
    return _struct_4fBf
