# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from tracking/Tracklet.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Tracklet(genpy.Message):
  _md5sum = "59fcd37fcd586a2228c557986fc973a2"
  _type = "tracking/Tracklet"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# Tracklet.msg
## Bounding box with class

# ID
uint8 id

# Bounding box
float32 x
float32 y
float32 w
float32 h

# class
uint8 clss

float32 score"""
  __slots__ = ['id','x','y','w','h','clss','score']
  _slot_types = ['uint8','float32','float32','float32','float32','uint8','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       id,x,y,w,h,clss,score

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Tracklet, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.id is None:
        self.id = 0
      if self.x is None:
        self.x = 0.
      if self.y is None:
        self.y = 0.
      if self.w is None:
        self.w = 0.
      if self.h is None:
        self.h = 0.
      if self.clss is None:
        self.clss = 0
      if self.score is None:
        self.score = 0.
    else:
      self.id = 0
      self.x = 0.
      self.y = 0.
      self.w = 0.
      self.h = 0.
      self.clss = 0
      self.score = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_B4fBf().pack(_x.id, _x.x, _x.y, _x.w, _x.h, _x.clss, _x.score))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 22
      (_x.id, _x.x, _x.y, _x.w, _x.h, _x.clss, _x.score,) = _get_struct_B4fBf().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_B4fBf().pack(_x.id, _x.x, _x.y, _x.w, _x.h, _x.clss, _x.score))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 22
      (_x.id, _x.x, _x.y, _x.w, _x.h, _x.clss, _x.score,) = _get_struct_B4fBf().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B4fBf = None
def _get_struct_B4fBf():
    global _struct_B4fBf
    if _struct_B4fBf is None:
        _struct_B4fBf = struct.Struct("<B4fBf")
    return _struct_B4fBf
