// Generated by gencpp from file detection/Detection.msg
// DO NOT EDIT!


#ifndef DETECTION_MESSAGE_DETECTION_H
#define DETECTION_MESSAGE_DETECTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace detection
{
template <class ContainerAllocator>
struct Detection_
{
  typedef Detection_<ContainerAllocator> Type;

  Detection_()
    : x(0.0)
    , y(0.0)
    , w(0.0)
    , h(0.0)
    , cls(0)
    , confidence(0.0)  {
    }
  Detection_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , w(0.0)
    , h(0.0)
    , cls(0)
    , confidence(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _w_type;
  _w_type w;

   typedef float _h_type;
  _h_type h;

   typedef uint8_t _cls_type;
  _cls_type cls;

   typedef float _confidence_type;
  _confidence_type confidence;





  typedef boost::shared_ptr< ::detection::Detection_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::detection::Detection_<ContainerAllocator> const> ConstPtr;

}; // struct Detection_

typedef ::detection::Detection_<std::allocator<void> > Detection;

typedef boost::shared_ptr< ::detection::Detection > DetectionPtr;
typedef boost::shared_ptr< ::detection::Detection const> DetectionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::detection::Detection_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::detection::Detection_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::detection::Detection_<ContainerAllocator1> & lhs, const ::detection::Detection_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.w == rhs.w &&
    lhs.h == rhs.h &&
    lhs.cls == rhs.cls &&
    lhs.confidence == rhs.confidence;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::detection::Detection_<ContainerAllocator1> & lhs, const ::detection::Detection_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace detection

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::detection::Detection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::detection::Detection_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::detection::Detection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::detection::Detection_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::detection::Detection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::detection::Detection_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::detection::Detection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b6ef12160302895f4532528b12bd7ec3";
  }

  static const char* value(const ::detection::Detection_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb6ef12160302895fULL;
  static const uint64_t static_value2 = 0x4532528b12bd7ec3ULL;
};

template<class ContainerAllocator>
struct DataType< ::detection::Detection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "detection/Detection";
  }

  static const char* value(const ::detection::Detection_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::detection::Detection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Detection.msg\n"
"## Bounding box with class and confidence\n"
"\n"
"# Constants\n"
"\n"
"# TODO\n"
"# uint8 car\n"
"# uint8 armor_module\n"
"# ...\n"
"\n"
"# Bounding box\n"
"float32 x\n"
"float32 y\n"
"float32 w\n"
"float32 h\n"
"\n"
"# class\n"
"uint8 cls\n"
"\n"
"float32 confidence\n"
;
  }

  static const char* value(const ::detection::Detection_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::detection::Detection_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.w);
      stream.next(m.h);
      stream.next(m.cls);
      stream.next(m.confidence);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Detection_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::detection::Detection_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::detection::Detection_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "w: ";
    Printer<float>::stream(s, indent + "  ", v.w);
    s << indent << "h: ";
    Printer<float>::stream(s, indent + "  ", v.h);
    s << indent << "cls: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.cls);
    s << indent << "confidence: ";
    Printer<float>::stream(s, indent + "  ", v.confidence);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DETECTION_MESSAGE_DETECTION_H
