// Generated by gencpp from file serial/Rune.msg
// DO NOT EDIT!


#ifndef SERIAL_MESSAGE_RUNE_H
#define SERIAL_MESSAGE_RUNE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace serial
{
template <class ContainerAllocator>
struct Rune_
{
  typedef Rune_<ContainerAllocator> Type;

  Rune_()
    : stamp()  {
    }
  Rune_(const ContainerAllocator& _alloc)
    : stamp()  {
  (void)_alloc;
    }



   typedef ros::Time _stamp_type;
  _stamp_type stamp;





  typedef boost::shared_ptr< ::serial::Rune_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::serial::Rune_<ContainerAllocator> const> ConstPtr;

}; // struct Rune_

typedef ::serial::Rune_<std::allocator<void> > Rune;

typedef boost::shared_ptr< ::serial::Rune > RunePtr;
typedef boost::shared_ptr< ::serial::Rune const> RuneConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::serial::Rune_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::serial::Rune_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::serial::Rune_<ContainerAllocator1> & lhs, const ::serial::Rune_<ContainerAllocator2> & rhs)
{
  return lhs.stamp == rhs.stamp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::serial::Rune_<ContainerAllocator1> & lhs, const ::serial::Rune_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace serial

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::serial::Rune_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::serial::Rune_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::serial::Rune_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::serial::Rune_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serial::Rune_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serial::Rune_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::serial::Rune_<ContainerAllocator> >
{
  static const char* value()
  {
    return "84d365d08d5fc49dde870daba1c7992c";
  }

  static const char* value(const ::serial::Rune_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x84d365d08d5fc49dULL;
  static const uint64_t static_value2 = 0xde870daba1c7992cULL;
};

template<class ContainerAllocator>
struct DataType< ::serial::Rune_<ContainerAllocator> >
{
  static const char* value()
  {
    return "serial/Rune";
  }

  static const char* value(const ::serial::Rune_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::serial::Rune_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Rune.msg\n"
"## From CV to CS : Rune coordinates\n"
"## DEPRECATED\n"
"\n"
"# Message\n"
"\n"
"time stamp\n"
;
  }

  static const char* value(const ::serial::Rune_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::serial::Rune_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Rune_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::serial::Rune_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::serial::Rune_<ContainerAllocator>& v)
  {
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERIAL_MESSAGE_RUNE_H
